<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Agency.DAL\Agency.DAL.csproj" />
    <ProjectReference Include="..\Agency.Domaine\Agency.Domaine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Mapper\" />
  </ItemGroup>

</Project>
